py_library(
    name = "pysyrenn",
    srcs = ["__init__.py"],
    deps = [
        "//pysyrenn/helpers:helpers",
        "//pysyrenn/frontend:frontend",
    ],
    visibility = ["//:__subpackages__"],
)
