py_test(
    name = "classify_lines",
    size = "small",
    srcs = ["classify_lines.py"],
    deps = [
        "//pysyrenn/frontend",
        "//pysyrenn/frontend/tests:helpers",
        "//pysyrenn/helpers:classify_lines",
    ],
)

py_test(
    name = "classify_planes",
    size = "small",
    srcs = ["classify_planes.py"],
    deps = [
        "//pysyrenn/frontend",
        "//pysyrenn/frontend/tests:helpers",
        "//pysyrenn/helpers:classify_planes",
    ],
)

py_test(
    name = "integrated_gradients",
    size = "small",
    srcs = ["integrated_gradients.py"],
    deps = [
        "//pysyrenn/frontend",
        "//pysyrenn/frontend/tests:helpers",
        "//pysyrenn/helpers:integrated_gradients",
    ],
)

py_test(
    name = "masking_network",
    size = "small",
    srcs = ["masking_network.py"],
    deps = [
        "//pysyrenn/frontend",
        "//pysyrenn/frontend/tests:helpers",
        "//pysyrenn/helpers:masking_network",
    ],
)

py_test(
    name = "netpatch",
    size = "small",
    srcs = ["netpatch.py"],
    deps = [
        "//pysyrenn/frontend",
        "//pysyrenn/frontend/tests:helpers",
        "//pysyrenn/helpers:netpatch",
    ],
)
